### ISSUE TITLE
Hue Entertainment API >PR> Hyperion.NG Master?

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [SJunkies/hyperion.ng#10]
Hi Sjunkies,

anscheinend hat das Hyperion.ng Projekt wieder an Fahrt aufgenommen und es scheint sich einiges für AMLOGIC-user im master getan zu haben... 
Planst Du deinen Entertainment-Branch in den master integrieren zu lassen?

Ich hoffe natürlich ja ;-)

Danke und viele Grüße
Anthax

**Comment by RickDB** [comment]
If @SJunkies is willing to make a PR can help out to get it merged in as this added feature would be awesome.

**Comment by otarie1** [comment]
Would love to see that happening!

**Comment by AnthraxLeprosyPi** [comment]
I hope he will find the time to do it. But I can't blame him - having never enough time for my hobbies myself...

**Comment by SJunkies** [comment]
@RickDB 
Sorry for the late reply ... but thank you for your offer! At the moment I do not need any help anymore, only the time for the implementation is very rare. But as far as I can tell, it does not take much longer ;)

**Comment by bennealon** [comment]
@SJunkies just wondering how far from completion this is? Is it usable, do you need testers? Any help needed with dev?
Would be awesome to see this over in the main project some time soon 👍
