### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [SJunkies/hyperion.ng#13]
Hi SJunkies,

ich weiß, Du bist beschäftigt...
Ich hatte eben versucht mal wieder den allerletzten Stand **(entertainment-api-2019)** zu bauen - leider bekomme ich auf die folgende Fehlermeldung:

`Scanning dependencies of target leddevice
[ 63%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDevice.cpp.o
[ 64%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceFactory.cpp.o
[ 64%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWrapper.cpp.o
[ 64%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/dev_serial/LedDeviceAdalight.cpp.o
In file included from /root/hyperion.ng/build/LedDevice_headers.h:15:0,
                 from /root/hyperion.ng/libsrc/leddevice/LedDeviceFactory.cpp:15:
/root/hyperion.ng/libsrc/leddevice/dev_net/LedDevicePhilipsHueEntertainment.h:96:5: error: 'mbedtls_x509_crt' does not name a type
     mbedtls_x509_crt cacert;
     ^~~~~~~~~~~~~~~~
[ 65%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/dev_serial/LedDeviceAtmo.cpp.o
In file included from /root/hyperion.ng/build/LedDevice_headers.h:15:0,
                 from /root/hyperion.ng/libsrc/leddevice/LedDeviceWrapper.cpp:7:
/root/hyperion.ng/libsrc/leddevice/dev_net/LedDevicePhilipsHueEntertainment.h:96:5: error: 'mbedtls_x509_crt' does not name a type
     mbedtls_x509_crt cacert;
     ^~~~~~~~~~~~~~~~
libsrc/leddevice/CMakeFiles/leddevice.dir/build.make:86: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceFactory.cpp.o' failed
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceFactory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
libsrc/leddevice/CMakeFiles/leddevice.dir/build.make:110: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWrapper.cpp.o' failed
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWrapper.cpp.o] Error 1
CMakeFiles/Makefile2:1915: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/all' failed
make[1]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
`

libmbedtls-dev ist natürlich installiert...

Evtl. fällt dir ja sofort was ins Auge.

Danke & Gruß
Anthrax

**Comment by SJunkies** [comment]
Hi @AnthraxLeprosyPi ,

"ich weiß, Du bist beschäftigt..." :) 
Ich habe immer ein offenes Ohr, vor allem für Input und Fehler!
Danke für die Fehlermeldung. Habe dir um mehr Leute zu erreichen, diesmal im Forum geantwortet.

[Philips HUE zu dunkel](https://hyperion-project.org/threads/philips-hue-zu-dunkel.493/page-8#post-15621)

Bekommen wir aber alles hin.

VG SJ
