### ISSUE TITLE
Hue Entertainment Wizard erzeugt falsche LED config

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [SJunkies/hyperion.ng#14]
Hi SJunkies,

ich habe gestern Abend mal Deine neueste Version mit allen Änderungen aus dem Haupt-Repo (token, database, etc.) probiert und es hat auf Anhieb super funktioniert!!!

Danke für alle Deine Mühen.

Beim Hue Entertainment Wizard ist mir allerdings folgendes aufgefallen:
Wenn ich zwei/mehrere Lampen mit dem gleichen Preset (bspw. bottom) ) versehe wird beim Erzeugen der config für beide Lampen die gleiche ID verwendet...

Zudem wäre es sehr hilfreich, wenn die Namen der Hue-Lampen irgenwie als Kommentar in der erzeugten Config auftauchen würden ;-)

Danke und Gruß
Anthrax

**Comment by SJunkies** [comment]
Hi @AnthraxLeprosyPi 

freut mich das alles soweit klappt...werde aber alles noch einmal umbauen müssen, wie im [PR#592](https://github.com/hyperion-project/hyperion.ng/pull/592) mit @Lord-Grey besprochen.

> Beim Hue Entertainment Wizard ist mir allerdings folgendes aufgefallen:
Wenn ich zwei/mehrere Lampen mit dem gleichen Preset (bspw. bottom) ) versehe wird beim Erzeugen der config für beide Lampen die gleiche ID verwendet...

Hab den Bug gefunden und ist mir selbst leider vorher nicht aufgefallen, da ich mit meiner (korrekten) Config gearbeitet habe. Beim verarbeiten der Daten ist alles korrekt, bis zum Punkt an dem im Script die Config gespeichert wird, dann überschreiben sich mehrfach vorhanden Presets immer mit dem letzteren.
Ein Fix dafür kommt bald und die Namen der Hues in der Config, habe ich auch schon eingearbeitet ;)

Danke dir und Gruß
SJ

**Comment by AnthraxLeprosyPi** [comment]
Hi SJunkies,

habe schon gelesen, dass es bei den Threads noch Potenzial gibt ;-)
Aber nichts desto trotz haben wir abends nun endlich wieder ein absolut geniales Ambilight im Wohnzimmer.

Bei Gelegenheit würde mich echt mal interessieren wie Deine Entwicklungsumgebung und der Workflow zum Debuggen aussieht - es juckt mir in den Fingern da auch mit anzupacken. Also falls du da mal ein paar Stichpunkte für mich hast würde ich gern mal tiefer eintauchen.

Achso eins noch: besteht die Möglichkeit (evtl. per Option) die Lampen auszuschalten sobald der Hyperion-Service gestoppt wird bzw. wenn der Ursprungszustand off war dann eben auch wieder auszuschalten? Ich hatte zudem gesehen, dass du da anscheinend schon länger am Thema Ursprungszustand forschst - hat das damit zu tun?

Wie immer Tausend Dank & Gruß
Anthrax
PS: Wenn jetzt bloß noch die Kids früher einschlafen würden....

**Comment by SJunkies** [comment]
> habe schon gelesen, dass es bei den Threads noch Potenzial gibt ;-)
> Aber nichts desto trotz haben wir abends nun endlich wieder ein absolut geniales Ambilight im Wohnzimmer.

Freut mich, das Ihr wieder euer Ambilight genießen könnt ;)
Ich selbst komme leider aktuell mal wieder nicht dazu, aber versuche auch den PR fertig zu bekommen.
 
> Achso eins noch: besteht die Möglichkeit (evtl. per Option) die Lampen auszuschalten sobald der Hyperion-Service gestoppt wird bzw. wenn der Ursprungszustand off war dann eben auch wieder auszuschalten? Ich hatte zudem gesehen, dass du da anscheinend schon länger am Thema Ursprungszustand forschst - hat das damit zu tun?

Genau das ist das Problem, was mit den Threads zutun hat und an dem ich seit Wochen arbeite und versuche eine Lösung zu finden. Daher auch der sehr späte PR, da es nicht für mich spricht, unfertige Arbeit abzuliefern - das ist nicht mein Style ;)
 
> Wie immer Tausend Dank & Gruß

sehr gern ;)

> Bei Gelegenheit würde mich echt mal interessieren wie Deine Entwicklungsumgebung und der Workflow zum Debuggen aussieht - es juckt mir in den Fingern da auch mit anzupacken. Also falls du da mal ein paar Stichpunkte für mich hast würde ich gern mal tiefer eintauchen.

Wie schon vor längerem einmal geschrieben...ich selbst hab auch keine wirkliche Entwicklungsumgebung...ich arbeite über Git und compiliere über meinem Raspberry 3B+ (mein 4GB 4er liegt leider seit Anfang Juli ungenutzt auf meinem Schreibtisch, da ich nicht dazu komme den endlich mal einzurichten...Schande über mein Haupt :/ ) zum Debuggen gehts direkt in den Code mit Ausgaben und Testen.
Mir fehlt leider selbst auch die Zeit um eine richtige Entwicklungsumgebung mit Dockern etc. aufzubauen, was aber längst überfällig wäre.
Aber aktuell komme ich damit gut zurecht, aber besser geht immer.

> PS: Wenn jetzt bloß noch die Kids früher einschlafen würden....

Haha....dabei kann ich dir leider keine Hilfe bieten :D

Wie gesagt, neuer Bugfix kommt bald, versuche noch das Hauptproblem mit dem Beenden zu lösen, dann hoffe ich sollte es auch der PR in den Master schaffen ;)

Grüße
SJ

**Comment by SJunkies** [comment]
@AnthraxLeprosyPi 

Fix ist im aktuellen [PR](https://github.com/hyperion-project/hyperion.ng/pull/592) eingearbeitet bzw. im [entertainment-api-2019 Branch](https://github.com/SJunkies/hyperion.ng/tree/entertainment-api-2019), ich hoffe es klappt nun alles ;)

Grüße
SJ
